# Generated by Django 4.1.4 on 2023-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='TotalPrice',
            new_name='totalPrice',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/image_2.png', null=True, upload_to=''),
        ),
    ]
